server:
  address: "0.0.0.0:9091"

theme: auto

session:
  redis:
    host: redis
    port: 6379
    username: default
  cookies:
    - domain: example.com
      authelia_url: https://auth.example.com

storage:
  local:
    path: /config/db.sqlite3

log:
  level: info

access_control:
  default_policy: deny
  rules:
    # BYPASS
    - domain:
        - auth.example.com
      policy: bypass
    # USERS
    - domain:
        - ask.example.com
      policy: one_factor
      subject:
        - group:users
    # ADMINS
    - domain:
        - users.example.com
      policy: two_factor
      subject:
        - group:admins

authentication_backend:
  ldap:
    address: ldap://lldap:3890
    base_dn: dc=example,dc=com
    user: uid=admin,ou=people,dc=example,dc=com
    users_filter: (&({username_attribute}={input})(objectclass=person))
    groups_filter: (member={dn})
    attributes:
      username: uid
      group_name: cn
      mail: mail
      display_name: displayName

regulation:
  max_retries: 3
  ban_time: 15m

notifier:
  filesystem:
    filename: /config/notification.txt
